//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: amessage.proto
namespace org.umundo.s11n.demo
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AMessage")]
    public partial class AMessage : global::ProtoBuf.IExtensible
    {
        public AMessage() { }

        //Message string
        private string _message = default(string);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string message
        {
            get { return _message; }
            set { _message = value; }
        }

        // NORMAL type 0
        // JOINED type 1
        // LEFT type 2
        // FLYCORD 3
        // FLYSTOPPED 4
        private int _type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int type
        {
            get { return _type; }
            set { _type = value; }
        }

        private string _flycordy;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"flycordy", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(string))]
        public string flycordy
        {
            get { return _flycordy; }
            set { _flycordy = value; }
        }

        private string _flycordx;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"flycordx", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(string))]
        public string flycordx
        {
            get { return _flycordx; }
            set { _flycordx = value; }
        }

        private string _username;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(string))]
        public string username
        {
            get { return _username; }
            set { _username = value; }
        }

        private int _score;
        [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name = @"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int score
        {
            get { return _score; }
            set { _score = value; }
        }

        private int _x;
        [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int x
        {
            get { return _x; }
            set { _x = value; }
        }

        private int _y;
        [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int y
        {
            get { return _y; }
            set { _y = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}
