// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatS11N.proto

package org.umundo.protobuf;

public final class ChatS11N {
  private ChatS11N() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    boolean hasFlyCordX();
    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    java.lang.String getFlyCordX();
    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    com.google.protobuf.ByteString
        getFlyCordXBytes();

    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    boolean hasFlyCordY();
    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    java.lang.String getFlyCordY();
    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    com.google.protobuf.ByteString
        getFlyCordYBytes();

    /**
     * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
     */
    boolean hasType();
    /**
     * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
     */
    org.umundo.protobuf.ChatS11N.ChatMsg.Type getType();
  }
  /**
   * Protobuf type {@code ChatMsg}
   */
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChatMsg)
      ChatMsgOrBuilder {
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatMsg defaultInstance;
    public static ChatMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ChatMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              message_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              flyCordX_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              flyCordY_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              org.umundo.protobuf.ChatS11N.ChatMsg.Type value = org.umundo.protobuf.ChatS11N.ChatMsg.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.umundo.protobuf.ChatS11N.internal_static_ChatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.umundo.protobuf.ChatS11N.internal_static_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.umundo.protobuf.ChatS11N.ChatMsg.class, org.umundo.protobuf.ChatS11N.ChatMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatMsg> PARSER =
        new com.google.protobuf.AbstractParser<ChatMsg>() {
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ChatMsg.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0, 0),
      /**
       * <code>JOINED = 1;</code>
       */
      JOINED(1, 1),
      /**
       * <code>LEFT = 2;</code>
       */
      LEFT(2, 2),
      /**
       * <code>FLYCORD = 3;</code>
       */
      FLYCORD(3, 3),
      /**
       * <code>FLYSTOPPED = 4;</code>
       */
      FLYSTOPPED(4, 4),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>JOINED = 1;</code>
       */
      public static final int JOINED_VALUE = 1;
      /**
       * <code>LEFT = 2;</code>
       */
      public static final int LEFT_VALUE = 2;
      /**
       * <code>FLYCORD = 3;</code>
       */
      public static final int FLYCORD_VALUE = 3;
      /**
       * <code>FLYSTOPPED = 4;</code>
       */
      public static final int FLYSTOPPED_VALUE = 4;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return JOINED;
          case 2: return LEFT;
          case 3: return FLYCORD;
          case 4: return FLYSTOPPED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.umundo.protobuf.ChatS11N.ChatMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ChatMsg.Type)
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLYCORDX_FIELD_NUMBER = 3;
    private java.lang.Object flyCordX_;
    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    public boolean hasFlyCordX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    public java.lang.String getFlyCordX() {
      java.lang.Object ref = flyCordX_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          flyCordX_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string FlyCordX = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFlyCordXBytes() {
      java.lang.Object ref = flyCordX_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flyCordX_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLYCORDY_FIELD_NUMBER = 4;
    private java.lang.Object flyCordY_;
    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    public boolean hasFlyCordY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    public java.lang.String getFlyCordY() {
      java.lang.Object ref = flyCordY_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          flyCordY_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string FlyCordY = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFlyCordYBytes() {
      java.lang.Object ref = flyCordY_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flyCordY_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private org.umundo.protobuf.ChatS11N.ChatMsg.Type type_;
    /**
     * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
     */
    public org.umundo.protobuf.ChatS11N.ChatMsg.Type getType() {
      return type_;
    }

    private void initFields() {
      username_ = "";
      message_ = "";
      flyCordX_ = "";
      flyCordY_ = "";
      type_ = org.umundo.protobuf.ChatS11N.ChatMsg.Type.NORMAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFlyCordXBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFlyCordYBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFlyCordXBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFlyCordYBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.umundo.protobuf.ChatS11N.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.umundo.protobuf.ChatS11N.ChatMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMsg)
        org.umundo.protobuf.ChatS11N.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.umundo.protobuf.ChatS11N.internal_static_ChatMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.umundo.protobuf.ChatS11N.internal_static_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.umundo.protobuf.ChatS11N.ChatMsg.class, org.umundo.protobuf.ChatS11N.ChatMsg.Builder.class);
      }

      // Construct using org.umundo.protobuf.ChatS11N.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        flyCordX_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        flyCordY_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = org.umundo.protobuf.ChatS11N.ChatMsg.Type.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.umundo.protobuf.ChatS11N.internal_static_ChatMsg_descriptor;
      }

      public org.umundo.protobuf.ChatS11N.ChatMsg getDefaultInstanceForType() {
        return org.umundo.protobuf.ChatS11N.ChatMsg.getDefaultInstance();
      }

      public org.umundo.protobuf.ChatS11N.ChatMsg build() {
        org.umundo.protobuf.ChatS11N.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.umundo.protobuf.ChatS11N.ChatMsg buildPartial() {
        org.umundo.protobuf.ChatS11N.ChatMsg result = new org.umundo.protobuf.ChatS11N.ChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.flyCordX_ = flyCordX_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.flyCordY_ = flyCordY_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.umundo.protobuf.ChatS11N.ChatMsg) {
          return mergeFrom((org.umundo.protobuf.ChatS11N.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.umundo.protobuf.ChatS11N.ChatMsg other) {
        if (other == org.umundo.protobuf.ChatS11N.ChatMsg.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasFlyCordX()) {
          bitField0_ |= 0x00000004;
          flyCordX_ = other.flyCordX_;
          onChanged();
        }
        if (other.hasFlyCordY()) {
          bitField0_ |= 0x00000008;
          flyCordY_ = other.flyCordY_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.umundo.protobuf.ChatS11N.ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.umundo.protobuf.ChatS11N.ChatMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object flyCordX_ = "";
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public boolean hasFlyCordX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public java.lang.String getFlyCordX() {
        java.lang.Object ref = flyCordX_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            flyCordX_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFlyCordXBytes() {
        java.lang.Object ref = flyCordX_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flyCordX_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public Builder setFlyCordX(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        flyCordX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public Builder clearFlyCordX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        flyCordX_ = getDefaultInstance().getFlyCordX();
        onChanged();
        return this;
      }
      /**
       * <code>optional string FlyCordX = 3;</code>
       */
      public Builder setFlyCordXBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        flyCordX_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object flyCordY_ = "";
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public boolean hasFlyCordY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public java.lang.String getFlyCordY() {
        java.lang.Object ref = flyCordY_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            flyCordY_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFlyCordYBytes() {
        java.lang.Object ref = flyCordY_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flyCordY_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public Builder setFlyCordY(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        flyCordY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public Builder clearFlyCordY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        flyCordY_ = getDefaultInstance().getFlyCordY();
        onChanged();
        return this;
      }
      /**
       * <code>optional string FlyCordY = 4;</code>
       */
      public Builder setFlyCordYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        flyCordY_ = value;
        onChanged();
        return this;
      }

      private org.umundo.protobuf.ChatS11N.ChatMsg.Type type_ = org.umundo.protobuf.ChatS11N.ChatMsg.Type.NORMAL;
      /**
       * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
       */
      public org.umundo.protobuf.ChatS11N.ChatMsg.Type getType() {
        return type_;
      }
      /**
       * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
       */
      public Builder setType(org.umundo.protobuf.ChatS11N.ChatMsg.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ChatMsg.Type type = 5 [default = NORMAL];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = org.umundo.protobuf.ChatS11N.ChatMsg.Type.NORMAL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChatMsg)
    }

    static {
      defaultInstance = new ChatMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ChatMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ChatS11N.proto\"\274\001\n\007ChatMsg\022\020\n\010username" +
      "\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\020\n\010FlyCordX\030\003 \001(" +
      "\t\022\020\n\010FlyCordY\030\004 \001(\t\022#\n\004type\030\005 \001(\0162\r.Chat" +
      "Msg.Type:\006NORMAL\"E\n\004Type\022\n\n\006NORMAL\020\000\022\n\n\006" +
      "JOINED\020\001\022\010\n\004LEFT\020\002\022\013\n\007FLYCORD\020\003\022\016\n\nFLYST" +
      "OPPED\020\004B\025\n\023org.umundo.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChatMsg_descriptor,
        new java.lang.String[] { "Username", "Message", "FlyCordX", "FlyCordY", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
